#requires -Version 7
<#
    Dot-sourced by TelegramBridge.ps1. NOT a module: these functions must
    share the bridge script's scope and $script: state.

    The manual in English, chapter for chapter with Bridge.Help.ps1.

    WHY THIS IS A SECOND FILE AND NOT CATALOGUE ENTRIES

    Everything else the bridge says goes through the catalogue in
    Modules/BridgeLanguage.psm1, one key per piece of text, precisely so the
    two languages sit together and a half-finished entry is a fact a test can
    state. The manual does not fit that shape:

      - a chapter is forty lines of prose, not a label, and forty lines in one
        catalogue value is not a string anybody can read or review; and
      - several chapters interpolate live settings mid-sentence, and the
        number lands in a different place in an English sentence than in an
        Arabic one. A {0} placeholder can move, but the surrounding clauses
        have to move with it, which is a rewrite rather than a substitution.

    So the structure is duplicated and the DRIFT IS GUARDED INSTEAD: a test in
    Bridge.Help.Tests.ps1 requires both languages to define exactly the same
    chapter keys, with the same AdminOnly flag, and a non-empty title and body
    for each. A chapter added to one language and not the other fails the gate
    by name. That is the trade this file makes, deliberately and once.
#>

function Get-HelpQuickStartTextEn {
    return (@(
            '🚀 Quick start'
            '━━━━━━━━━━━━━━'
            'Your first template on air, in six steps:'
            ''
            '1️⃣ Press 📋 Templates.'
            '2️⃣ Choose the template you want.'
            '3️⃣ Type the text for each field it asks for, or ⏭ skip the ones you do not need.'
            '4️⃣ A review screen shows what you are about to put on air — read it.'
            '5️⃣ Press ✅ Confirm. It is on air.'
            '6️⃣ To take it off: the red row at the top of the main menu. Press it.'
            ''
            '━━━━━━━━━━━━━━'
            'Three rules that will save you:'
            '• Every template passes a review before air, so nothing is published by one press.'
            '• 🏠 Menu returns you to the main screen at any moment, even mid-typing.'
            '• The red rows at the top are what the bridge believes is on air right now.'
            ''
            '📖 For detail: open the help index and pick what concerns you.'
        ) -join "`n")
}

function Get-HelpChaptersEn {
    <# The same chapters as Get-HelpChapters, in English. Keys, order and
       AdminOnly must match it exactly; a test enforces that. #>
    param([long]$ChatId = 0, [long]$UserId = 0)
    if ($UserId -eq 0) { $UserId = $ChatId }

    $chapters = @(
        @{ Key = 'show'; Title = '▶️ Putting a template on air'; AdminOnly = $false; Body = @(
                '📋 Templates → pick one → fill each field → review → confirm.'
                '↳ Every template passes a review screen before air, even one with no fields.'
                '↳ ⭐ Favourites sit at the top of the menu, one press away.'
                ''
                '⏭ Skip any field you do not want to fill; it stays empty on screen.'
                '🔖 Each operation gets a short reference in 🧾 My operations — quote'
                '   it to an administrator if you need them to find it in the log.'
            ) }
        @{ Key = 'edit'; Title = '✏️ Editing while it is live'; AdminOnly = $false; Body = @(
                '✏️ Update text → the template → the field → the new text.'
                '↳ Changes the words without replaying the template animation.'
                '🔁 Repeat with edits: brings back the last template with its values to change.'
                '↩️ Undo: appears in the menu after any operation and restores the'
                '   previous state, within its window.'
                ''
                '📋 An edit starts from the current text, not from nothing: it is shown'
                '   to you and copied with one press — on it or on the copy button —'
                '   then pasted and changed.'
                '↳ The text that will appear on screen is always in a fixed-width font,'
                '   so it cannot be confused with the field names describing it.'
                ''
                '⏳ If you are interrupted mid-typing, a warning arrives a minute before'
                '   the timeout with an extend button that resets it, so what you were'
                '   writing is not lost.'
                '↳ The news ticker draft gets the same warning before it expires.'
                '↳ And if the bridge restarts while you are half-way through, your draft'
                '   comes back and a message says so — so your next message does not'
                '   become the text of a template without your knowing.'
            ) }
        @{ Key = 'stop'; Title = '🛑 Ending and emergencies'; AdminOnly = $false; Body = @(
                '🔴 The rows at the top of the menu are what the bridge sees on air now.'
                '↳ Press a row to hide that layer straight away.'
                '🚨 Hide everything: lists the layers, then asks for confirmation.'
                '🚪 Exit the scene: plays the scene ending instead of cutting it.'
                '↳ With confirmation on, the template name, its air time and who sent it'
                '   are shown before it runs.'
                '🕓 If Cinegy accepted the hide but has not confirmed the layer is clear,'
                '   the message says so, and the layer stays listed as on air until the'
                '   confirmation arrives — so it is not lost from sight while it may'
                '   still be showing.'
                ''
                '🔒 If a layer is protected for administrators or the owner, the typed'
                '   command is refused exactly as the button refuses it.'
                '⚡ Hide and exit outrank show inside the same batch, so an emergency'
                '   never waits behind a show.'
            ) }
        @{ Key = 'trouble'; Title = '🆘 When something goes wrong'; AdminOnly = $false; Body = @(
                'The screen says "failed" and you do not know why:'
                '↳ 🔍 Why did it not appear? under the failure message: is Cinegy'
                '   responding, is the scene file where it should be, who holds the'
                '   layer. A read-only check.'
                '↳ 🧾 My operations names the reason and the right next step for it.'
                '↳ Copy the 🔖 reference and send it to an administrator; it finds the'
                '   operation line in the log.'
                ''
                'A graphic is on screen and the bridge does not know it, or the reverse:'
                '↳ 🎚 Layers reads Cinegy directly and compares — "external" means'
                '   something was shown from outside the bridge.'
                '↳ 📸 A frame from air settles it by eye.'
                ''
                'Nothing responds at all:'
                '↳ ℹ️ Status shows whether Air is unreachable.'
                '↳ Tell an administrator; their health centre shows where the fault is.'
            ) }
        @{ Key = 'time'; Title = '⏱ Timing and scheduling'; AdminOnly = $false; Body = @(
                '⏱ Timed show: shows the template and hides it automatically after the time.'
                '↳ A timer can be attached to a template already on air from the ⏱ button beside it.'
                '📅 Scheduling: the template, the values and the time, then once, daily or weekly.'
                ''
                '🔔 If a template stays on air a long time you get an alert with the text'
                '   on screen, a "🙈 hide it" button to pull it at once, and a'
                '   "✅ handled" button to acknowledge it. Without an acknowledgement,'
                '   one follow-up arrives after it.'
                '↳ Timers and alerts are saved, so they survive a restart of the bridge.'
            ) }
        @{ Key = 'urgent'; Title = '🚨 The urgent board'; AdminOnly = $false; Available = (Test-UrgentBoardAvailable); Body = @(
                'Breaking lines shown one after another at a steady rhythm, without'
                '   stopping at each one to type and publish it by hand.'
                '🚨 Urgent → ➕ add a line → ✅ tick what plays → ▶️ run.'
                '⏭ Skip shows the next at once; skipping the last, or ⏹ stop, ends the run.'
                '⏸ Pause keeps the current item up and freezes the advance; ▶️ resume continues.'
                '↳ The template safety timer does not pause. Adjust interval and repeats with the buttons.'
                '⏱ Each line may set its own interval; otherwise the general one applies.'
                '↳ 🔁 cycle replays the whole board (1 2 3 · 1 2 3); item repeats each'
                '   line then moves on (1 1 · 2 2). The total-time ceiling trims both.'
                '🎬 text swaps the words in the standing scene; exit takes it out and'
                '   brings it back with the next line. 🙈 hide-after takes the current'
                '   one out before the next.'
                '⏳ The gap between stories leaves the screen empty between one and the'
                '   next in exit mode, and raises the shortest allowed interval by the same amount.'
                '⚙️ Board timings; and each line has its own overrides from the ⚙️ button beside it.'
            ) }
        @{ Key = 'news'; Title = '📰 The news ticker'; AdminOnly = $false; Body = @(
                'The ticker is edited as a draft, and reaches air only when published.'
                ''
                '✏️ Start editing: opens a draft and locks it in your name so two people cannot edit at once.'
                '➕ Add a headline · 📝 edit and reorder · 👁 preview.'
                '📥 Import TXT: a text file replaces the draft or is added to it.'
                '🕘 Backups and restore: every publish keeps a copy you can go back to.'
                ''
                '📊 ⬇️ Pull and publish, and 📝 pull into the draft, fetch the sheet (if'
                '   its link is set). The detail is in the Google Sheets chapter.'
                ''
                '🔒 If a colleague holds the draft: 🔓 request the lock sends them a request.'
                ''
                '🚪 Three ways a draft ends. Choose deliberately:'
                '↳ ✅ Review and publish: shows what will change, then publishes and unlocks.'
                '↳ 🤝 Hand the draft to the next person: it is neither deleted nor put on'
                '   air; it keeps every headline and whoever presses ✏️ first continues'
                '   it — for leaving mid-job.'
                '↳ 🗑 Discard the draft: sends you its headlines as a message, then deletes it.'
                ''
                '⏳ A draft left untouched expires: you get a warning first, the text of'
                '   what was written after, and a button to resume it.'
                '🧾 Execution log: did the automatic sheet sync run, when, and how many'
                '   headlines it published — it publishes to air on its own clock.'
            ) }
        @{ Key = 'sheet'; Title = '📊 The Google Sheets link'; AdminOnly = $false; Body = @(
                'The sheet and the ticker are two faces of one content: what is in the'
                'sheet reaches air, and what is published from the bot returns to the sheet.'
                ''
                '📄 The shape of the sheet:'
                '↳ One headline per row, from the first column only.'
                '↳ The following columns are editor notes and never reach air.'
                '↳ An empty row is ignored, and a comma inside a cell does not split the headline.'
                ''
                '⬇️ From the sheet to air:'
                '↳ "⬇️ Pull and publish" fetches the sheet and puts it on air after confirmation.'
                '↳ "📝 Pull into the draft" fetches it for review and ordering, and nothing'
                '   reaches air until you press "✅ Review and publish".'
                '↳ The confirmation tells you how many headlines will be replaced beforehand.'
                '↳ An empty sheet is refused and does not clear the ticker — if clearing'
                '   is what you meant, clear it by hand from the news screen.'
                ''
                '⬆️ From the bot to the sheet:'
                '↳ Every publish from Telegram is written to the sheet too, so there is no copying by hand.'
                '↳ If the sheet refuses the write, what is on air stays published and you'
                '   are told that only the saving failed.'
                ''
                '🔒 The draft and the lock:'
                '↳ The automatic sync skips its turn while a draft is open, so half a line'
                '   a colleague is writing is not wiped.'
                '↳ If somebody else holds the draft: "🔓 request the lock"; replacing it'
                '   directly is for an administrator alone, and with a confirmation.'
            ) }
        @{ Key = 'mojaz'; Title = '📑 The bulletin'; AdminOnly = $false; Available = (Test-MojazAvailable); Body = @(
                'A full bulletin from a table: each row an image, a headline and a story,'
                '   played in order inside one scene that is not re-shown between them.'
                ''
                '📚 The library: keep as many bulletins as you like, each with its own name, rows and timing.'
                '↳ ➕ New bulletin · ✏️ rename · 📋 duplicate · 🗑 delete.'
                '↳ Deleting cancels its scheduled runs with it, and is refused while it is on air.'
                ''
                '➕ Add a row: image, then headline, then story.'
                '✏️ By row number: change its image, headline or story without deleting it.'
                '⬆️ ⬇️ to reorder · 🗑 to delete a row · 🧹 to clear the table.'
                ''
                '🖼 Three image choices per row:'
                '↳ 🖼 Its own image: uploaded from your phone or given as a path.'
                '↳ ↑ Follow the previous: the image does not change — this is how one'
                '   image serves several rows.'
                '↳ ▫️ The template image: back to the scene''s own.'
                '↳ An image already uploaded in this bulletin is reused with one press.'
                '↳ What you upload is checked, sized to the template and saved as PNG;'
                '   anything that is not an image is refused rather than becoming a row'
                '   that shows nothing.'
                '↳ The 🖼 column tells you which of the three each row is.'
                ''
                '🎬 Reveal sync — what it is and why:'
                '↳ The scene loops, and at the loop point the content vanishes and returns with the reveal.'
                '↳ Off: the story is written at its own time, and the viewer may see it change in front of them.'
                '↳ On: it is written inside that reveal, so the new story looks as if it'
                '   has just come in — no visible swap.'
                '↳ Its price is that the rhythm becomes the loop length, not the time you'
                '   wrote: a one-minute loop means a story a minute whatever you set.'
                '↳ To change the rhythm then, cut LoopEndFrame in Titler.'
                ''
                '⏱ Duration: how long each row holds · ⏩ first: extra for the entrance ·'
                '   ⏹ last: how long it holds before the exit. Zero follows the template.'
                ''
                '▶️ Run · ⏹ stop and exit.'
                '🕒 Run later: a saved time that survives a restart of the bridge.'
                '🕒 Schedule: every upcoming time, and cancelling any of them.'
                '↳ A scheduled run plays the latest saved version, not the one booked.'
                '↳ Two times together do not collide: the second waits and you get one notice.'
                '↳ Editing the table mid-run changes the next time, not what is showing now.'
                '🧾 The execution log on the schedule screen: did last night''s bulletin'
                '   actually start, how late was it, and why it failed if it did.'
                ''
                '🚨 Breaking news outranks it: an urgent item going to air pulls the'
                '   bulletin. Before sending you are asked: now, or after the bulletin'
                '   ends? A deferred one goes out by itself.'
                '↳ Starting a bulletin while an urgent item is on air asks the same.'
                '⏹ "Stop the bulletin" in the main menu stops the run and leaves by the exit animation.'
            ) }
        @{ Key = 'boards'; Title = '🗂 Programme content'; AdminOnly = $false; Available = (Test-BoardsAvailable); Body = @(
                'A prepared table of texts for a programme: the producer writes the'
                '   episode''s texts in advance, and on air the operator presses the line they want.'
                ''
                '📐 **Every board is bound to a template you choose**, and the template'
                '   decides two things: each row''s fields, and the layer it goes out on.'
                '↳ The fields are read from the scene itself, never typed or invented.'
                '↳ So a board on a two-field template is a row of two fields, no more.'
                ''
                '🆕 Creating one is two steps (administrator): "➕ New board"'
                '↳ **Step 1:** choose the template. Each shows how many fields it has.'
                '   ✅ usable · ⛔ ineligible with the reason (a scene that declares no'
                '   text field cannot carry a board, so it is not offered and then failed).'
                '↳ **Step 2:** name the board as the operator will see it on the button.'
                '↳ The template **does not change after creation**: another programme means another board.'
                '↳ The board header always states its template, its layer and its field names.'
                ''
                '⚙️ Its settings are in ⚙️ Settings → 🗂 Programme content:'
                '↳ "Programme content boards" opens the whole door (off by default).'
                '↳ "Maximum boards" and "maximum rows per board".'
                ''
                '➕ New row: fill its fields one at a time.'
                '📋 Paste a batch: one line per row, fields separated by |'
                '↳ A short line has its remaining fields left empty; an over-long one is'
                '   refused by line number with the reason.'
                ''
                '⬆️ ⬇️ reorder · ✏️ edit a field · 🗑 delete a row.'
                '🔕 Disable a row: its text is kept and not shown — you prepared ten and today need six.'
                ''
                '▶️ Show the row · ⏹ hide it. The show goes through the usual path, so'
                '   the layer protection, the audit trail and "what is on air" are unchanged.'
                ''
                '🛡 "Who may fill it" (administrator): a button cycling between everyone,'
                '   administrators and the owner, showing the current one. Showing and'
                '   hiding stay with whoever holds the template''s own permission.'
                '🗑 Delete the board (administrator), with a confirmation.'
                ''
                '✂️ If the scene is re-cut and a field disappears: your text is kept and'
                '   not sent, and the screen says the field is gone.'
                'Text only — images are outside this door deliberately.'
            ) }
        @{ Key = 'track'; Title = '🔍 Watching and checking'; AdminOnly = $false; Body = @(
                'ℹ️ Status: a quick summary of the Air server, the channel and the tracked templates.'
                '🎞 Material schedule: what the Cinegy schedule plays today. Read only, no editing.'
                '🤝 Handover: what is on air, the coming times and unhandled failures on'
                '   one screen, with a free note line and an acknowledgement from whoever takes over.'
                '🎚 Layers: reads Cinegy directly and compares it with the bridge record.'
                '↳ Per layer: showing, external, hidden, or unknown.'
                '📸 A frame from air: a recent still of the channel output.'
                '🧾 My operations: your latest operations with a retry and a reference for each.'
                '📅 The operation log (from 🧾 My operations, 📊 Reports or 📜 the audit):'
                '↳ A 24, 48 or 72 hour or 7 day window, with what you have read marked.'
                '↳ 📆 yesterday, then ◀ and ▶ to move back a day at a time.'
                '↳ A table of time, operation, template and result, with a verdict above'
                '   it saying whether the period held a failure or a refusal.'
                '↳ It reads the audit trail, not memory, so it survives a restart.'
                '↳ An administrator gets a 👥 all operators button for the same period.'
                '🕘 What did I miss: what happened while you were away and who did it.'
                '📊 Reports: banners and headlines over a period, with a file to download.'
                '🆕 What''s new: a summary of what recent versions changed.'
                ''
                '⚠️ The line at the top of the menu says when the bridge last checked.'
                '↳ If a warning appears there, the information may not match the screen — confirm with a still.'
            ) }
        @{ Key = 'notices'; Title = '🔔 Notifications'; AdminOnly = $false; Body = @(
                'Any template can announce itself when it goes on air and when it comes'
                '   off, and an administrator decides which templates do and to whom.'
                ''
                '📨 What the notice tells you:'
                '↳ The template name and layer, and the story text as it will read on screen.'
                '↳ The duration: "hides automatically after ..." or "stays until hidden by'
                '   hand", and on removal: how long it was on air.'
                '↳ And who did it. You are never notified about your own operation.'
                ''
                '🔕 Every notice carries a "stop my alerts" button, for you alone.'
                '↳ To come back, send the alerts command at any time.'
                '⏸ A notice does not interrupt you mid-typing: it is held until you finish'
                '   and then arrives together in one message.'
                '⚠️ Except one, which reaches you at once even with your alerts off: that'
                '   the template you are preparing right now has been shown or removed —'
                '   check what you prepared before sending, because the screen has changed.'
                ''
                '🔁 One template is not reported more than once every half minute, so a'
                '   run of corrections to one headline does not become three interruptions.'
                ''
                '🌙 Quiet hours (set by an administrator): anything not urgent is held'
                '   overnight and arrives together in one digest when the period ends.'
                '↳ And anything meaning the screen is wrong now — a black output, a'
                '   graphic that will not come off — arrives at once whatever the hour.'
                '↳ What is held is saved, so it is not lost if the bridge restarts overnight.'
                ''
                '⚙️ For an administrator: "Show notices per template" in Settings — a'
                '   screen with every template; press one to cycle it between:'
                '↳ 🔕 nobody → 👮 administrators → 📢 everyone authorised.'
            ) }
        @{ Key = 'settings'; Title = '⚙️ Settings'; AdminOnly = $true; Body = @(
                'Everything that changes how the bridge behaves is here. A change takes'
                '   effect at once and is saved to config.json without a restart, except'
                '   where it says otherwise on saving.'
                ''
                '🌐 Language: the 🌐 button on this screen switches the whole bridge'
                '   between Arabic and English, for everyone, immediately.'
                ''
                '🎛 Most values are set by pressing, not typing:'
                '↳ Numbers: ➖ and ➕ at a step suited to their size, showing the default'
                '   and the range, with a ⌨️ button for anyone who knows the exact figure.'
                '↳ Hours and weekdays: a grid to choose from, with the current one marked.'
                '↳ The maintenance window: an hour then a quarter, and a 🚫 button to clear it.'
                '↳ Template, layer and duration lists: a picker that cannot be misspelled.'
                '🔒 Any setting whose name looks like a code or a token is shown by its'
                '   length, not its text, in lists; only its own screen shows the value to copy.'
                '↳ And sensitive numbers have a range that refuses anything outside it.'
                ''
                '🤏 One-hand mode: one full-width button per row, on every screen and not'
                '   the menu alone — for holding the phone in one hand, with one thumb,'
                '   against the clock.'
                ''
                '🗂 The eleven doors:'
                '↳ 🔐 Security · 🔴 On air · 📚 Templates · 📰 News ticker.'
                '↳ 🚨 The urgent board · 🗂 Programme content.'
                '↳ 📅 Scheduling · 📊 Monitoring · 🗄️ Files and retention · 🔔 Notifications.'
                '↳ 🛠️ Advanced.'
                '↳ Every setting is in exactly one door, and every button shows its current value.'
                ''
                '🔎 Finding things quickly:'
                '↳ "🔎 Search" takes the setting name or part of its description.'
                '↳ "📝 Changed only" lists what differs from the default — the first place'
                '   to look when the bridge behaves unexpectedly.'
                '↳ "🧭 Simple" is what daily running needs; "🛠 Advanced" is the rest.'
                ''
                '✏️ Editing:'
                '↳ A yes/no setting flips with one press.'
                '↳ A numeric one is set with ➖ and ➕; anyone who knows the number types'
                '   it from ⌨️. Anything outside the range is refused and nothing changes.'
                '↳ A setting with fixed choices is shown as buttons, so a typo cannot break it.'
                '↳ Every change is written to 📜 the audit with the name of whoever made it.'
                ''
                '🔐 Show and hide permission, per template and per layer:'
                '↳ "Administrator-only templates" and "owner-only templates": who may show and hide this template.'
                '↳ "Administrator-only layers" and "owner-only layers": protects the layer'
                '   whatever template is put on it.'
                '↳ Empty means everyone, and that is the default. When two rules apply the'
                '   stricter wins: an administrator template on an owner layer becomes owner-only.'
                '↳ Automatic hiding is never blocked — the hide timer, hide-all, and the'
                '   bulletin exit — because a graphic left on air is worse.'
                ''
                '🔒 Protection settings:'
                '↳ They show a lock and ask for confirmation when weakened, not when strengthened.'
                '↳ They are: RequireUserLevelAuth, EnableSelfServiceRequests,'
                '   EnableRawCommand, EnableFullTemplateManagement,'
                '   EnableDpapiSecrets, BlockRejectedRequesters,'
                '   LeaveUnknownGroups, TemplateAirExtensionEnabled.'
                ''
                '♻️ Undoing:'
                '↳ Every setting has a button returning it to the default, with a'
                '   confirmation, and "restore defaults" returns all of them.'
                "↳ 🗄 Settings backups: every save leaves a copy, and $(Get-SettingInt 'ConfigBackupKeepFiles' 1) are kept."
                '↳ Restoring shows a table: the setting, its value now, and its value in'
                '   the backup — then saves the current one before writing, and needs a restart after.'
                '↳ Secret values are shown by length, not content, and lists by their number of entries.'
                ''
                '📤 Moving between machines:'
                '↳ Export takes the settings alone: no BotToken and no user lists.'
                '↳ Import shows what will change, refuses any key it does not know, and'
                '   applies nothing without a confirmation.'
            ) }
        @{ Key = 'admin'; Title = '🛡️ Administrator tools'; AdminOnly = $true; Body = @(
                '⚙️ Settings and 👤 Access requests are in the main menu.'
                '🗂 Admin tools holds the rest:'
                '↳ 👥 Users, ⚡ ready-made texts, 📚 templates.'
                '↳ ▶️ The live relay and 🔗 the stream link.'
                '↳ 📡 The feed watch: arriving or not and since when, the source'
                '   and the cycle, and the last day''s outages with their lengths.'
                '↳ 📜 The audit, 🧪 diagnostics and 🛠 the raw command.'
                '↳ ✅ Shift readiness: layers on air, pending operations, a ticker draft,'
                '   quarantined chats and standing faults, then a verdict or a list.'
                '↳ Under it, 🛡 the disabled protections with their effect and the name of'
                '   their setting — three ship off. They are a choice, so they do not'
                '   enter the "ready" verdict.'
                '↳ 🗄 Template backups in 📚 Templates: a restore names what it will delete'
                '   and change before writing, and is refused if it touches a template on'
                '   air or scheduled.'
                '🔇 Two hours quiet: in ⚙️ Settings → Monitoring, beside the scheduled'
                '   quiet hours. It holds only the non-urgent, and ends by itself on a restart.'
                '🩺 The health centre: Telegram, Cinegy, the output, storage and'
                '   scheduling on one screen, with 🗂 the runtime files and a usage line.'
                '🧪 Live path check: a full show-and-hide cycle on the test layer,'
                '   reporting the result of each step. It needs TemplateTestLayer unused.'
                '📤/📥 Settings: moving the configuration between machines. The export'
                '   carries no token and no user list, and the import shows what will'
                '   change before applying it.'
                '♻️ Restart the bridge: with a confirmation, and after checking a service exists to bring it back.'
                ''
                '🖤 Output monitoring — how you know the channel is alive:'
                $(if ((Get-SettingInt 'OutputMonitorMinutes' 0) -le 0) { '↳ Monitoring is off right now (OutputMonitorMinutes = 0).' }
                    else { "↳ The bridge grabs a frame from the channel output every $(Get-SettingInt 'OutputMonitorMinutes' 1) minute(s)." })
                '↳ It looks at the picture itself, not at what Cinegy says about itself.'
                "↳ If the frame comes back black it does not warn at once: it waits $(Get-SettingInt 'OutputBlackConfirmSeconds' 1)s and grabs another."
                '↳ The warning arrives only if both are black — a deliberate break or'
                '   fade does not wake anybody.'
                '↳ It warns once, then reports the recovery when the picture returns.'
                '↳ Set OutputMonitorMinutes to 0 to stop monitoring entirely.'
                ''
                '❤️ Cinegy health — where the warning numbers come from:'
                "↳ Read from the engine counters every $(Get-SettingInt 'CinegyHealthCheckSeconds' 1)s: the last minute''s samples."
                "↳ A dropped frame counts as a fault only if it passes $(Get-SettingInt 'CinegyFrameLossTolerance' 0) frames AND $(Get-Setting 'CinegyFrameLossTolerancePercent')% of the output together."
                "↳ The state does not change until $(Get-SettingInt 'CinegyHealthConfirmChecks' 1) consecutive checks agree,"
                "   and then no warning arrives until $(Get-SettingInt 'HealthFailureAlertThreshold' 1) consecutive failures."
                '↳ If the alerts are too many, raise the percentage or the number of checks in ⚙️ Settings.'
            ) }
        @{ Key = 'access'; Title = '🚪 Who gets into the bot'; AdminOnly = $true; Body = @(
                'Strangers find the bot, and every one of its locks has a key in ⚙️ Settings.'
                ''
                '👤 Access requests: who is waiting, since when, and when their request expires.'
                '↳ ✅ Approve asks a second time before it runs — granting access to the'
                '   air does not happen on a stray press — then adopts the name the'
                '   requester sent.'
                '↳ Every approval is reported to all administrators with the name of whoever granted it.'
                '↳ ❌ Reject removes the request and blocks the chat so it can never ask'
                '   again. Turn off "block a rejected requester" for rejection without a block.'
                ''
                '📜 Past requests (a button on the requests screen): who asked, the state'
                '   (approved, rejected or awaiting a decision), when it was decided, by'
                '   whom, and how long they waited.'
                ''
                '📡 Every administrator gets the administrator notice, whether they are in'
                '   AdminChatIds or AdminUserIds — and 🧪 diagnostics warns you if the'
                '   two lists differ.'
                ''
                '🚫 The blocked (from the requests screen): the reason, the date, who'
                '   blocked them, and a button lifting the block on any chat.'
                '↳ A blocked party is never told they are blocked — anyone who knows opens another account.'
                ''
                '🔑 The join code: set it and a stranger is asked for it before their request reaches you.'
                "↳ $(Get-SettingInt 'JoinSecretMaxAttempts' 0) wrong attempts in a day block the chat, with no message."
                '↳ The code is shown and logged by its length, not its text. Send - to clear it.'
                "↳ And each chat gets $(Get-SettingInt 'MaxAccessRequestsPerDay' 0) requests a day, no more."
                ''
                "😴 Each day you are told who has not used the bot for $(Get-SettingInt 'DormantUserDays' 0) days."
                '↳ "Disable dormant users automatically" actually disables them rather than only reporting.'
                '↳ The owner is never listed, and anyone with no history is not counted.'
                ''
                '🚪 Groups: the bot leaves any group it is added to, and tells you.'
                '↳ A group in AllowedChatIds is not unknown, so it is not left.'
            ) }
        @{ Key = 'back'; Title = '↩️ Going back and cancelling'; AdminOnly = $false; Body = @(
                '• ⬅️ Back at the bottom of every screen goes one step back.'
                '• 🏠 Menu returns you to the main screen at any time, even mid-typing.'
                '  The phone''s own back button leaves the conversation entirely and the'
                '  bot cannot intercept it, so use the on-screen buttons instead.'
                '• ☰ beside the text box lists every command.'
                '• The cancel command abandons the current operation, and the menu command opens the menu.'
            ) }
    )

    $isAdmin = Test-Admin -ChatId $ChatId -UserId $UserId
    if ($isAdmin) {
        $sheet = @($chapters | Where-Object { $_.Key -eq 'sheet' })[0]
        $sheet.Body += @(
            ''
            '⚙️ Setting it up (administrator):'
            '↳ "Google Sheets link (CSV)" in ⚙️ Settings: the CSV export link, not the'
            '   ordinary sheet link, and the sheet shared as "anyone with the link".'
            "↳ ""Sheet sync mode"" is manual or automatic, with the sync interval ($(Get-SettingInt 'NewsSheetSyncMinutes' 1) min), the download timeout, and who is told about a change."
            '↳ Writing back needs a Google Apps Script published as a web app. Its link'
            '   and secret live in config.json beside BotToken, not inside Settings, so'
            '   they do not leave in a settings export. The steps are in'
            '   docs/news-sheet-writeback.gs; restart the bridge afterwards.'
            '↳ The script replaces the first column only; notes in the other columns stay.'
        )
    }

    if (Test-StatusViewer -ChatId $ChatId -UserId $UserId) {
        $track = @($chapters | Where-Object { $_.Key -eq 'track' })[0]
        $track.Body += '📊 Full status: for an administrator and the owner; checks the source by hand and shows the monitoring server state.'
    }

    $available = @($chapters | Where-Object { -not $_.ContainsKey('Available') -or [bool]$_.Available })
    return @($available | Where-Object { -not $_.AdminOnly -or $isAdmin })
}
